# Generated by Django 3.1.5 on 2021-01-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_partnerusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerusers',
            options={'verbose_name': 'Зарегистрированный пользователь', 'verbose_name_plural': 'Зарегистрированные пользователи'},
        ),
    ]
