# Generated by Django 3.1.5 on 2021-01-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationOfDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationForMembership', models.FileField(upload_to='uploads/', verbose_name='Заявление о вступлении')),
                ('passportSides', models.FileField(upload_to='uploads/', verbose_name='Паспорт - лицевая и обратная сторона на одной странице')),
                ('addressReference', models.FileField(upload_to='uploads/', verbose_name='Адресная справка - с ЦОН')),
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документ',
            },
        ),
    ]
