# Generated by Django 3.1.5 on 2021-01-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_verificationofdocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeAPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entranceFee', models.IntegerField(blank=True, verbose_name='Сумма взноса')),
                ('dateOfPayment', models.DateField(blank=True, null=True, verbose_name='Дата платежа')),
                ('paymentMethod', models.CharField(choices=[('bank', 'Банковский'), ('cash', 'Наличные')], default='Банковский', max_length=30, verbose_name='Метод оплаты')),
                ('document', models.FileField(upload_to='uploads/', verbose_name='Обзор...')),
            ],
        ),
    ]
